# External gems
# See http://ixti.net/software/2013/01/28/using-jekyll-plugins-on-github-pages.html for making `jekyll archives` work.
gems:
  - jekyll-sitemap
  - jekyll-paginate

exclude:
  - "/vendor/"

# Site settings
title: Melbourne Chelsea Supporters Club
subtitle: "The Home Page of Melbourne Chelsea"
email: admin@melbournechelsea.com.au
# name: Adam Miritis
# description: >
cover: "/assets/header_image.jpg"
logo: "/assets/logo.png"

# Build settings
markdown: kramdown
paginate: 5
paginate_path: "/page:num/"
inter_post_navigation: false
highlightjs_theme: "monokai-sublime"

# Disqus comments
# disqus_shortname: bencentra

# Google analytics
# ga_tracking_id: "UA-XXXX-1"

# Category descriptions (for archive pages)
descriptions:
  - cat: Membership
    desc: "Posts describing both local and True Blue membership"
  - cat: Information
    desc: "Posts containing website information"

# Social icons and sharing options
#
# Social settings are used in two places:
# * In the footer, as links to your personal profiles
# * After each blog post for sharing widgets
#
# Example:
#
# social:
#   - name: Twitter                         # Name of the service
#     icon: twitter                         # Font Awesome icon to use (minus fa- prefix)
#     username: "@TheBenCentra"             # (User) Name to display in the footer link
#     url: https://twitter.com/TheBenCentra # URL of your profile (leave blank to not display in footer)
#     desc: Follow me on Twitter            # Description to display as link title, etc
#     share: true                           # Include in the "Share" section of posts
social:
  - name: Twitter
    icon: twitter
    username: Melbourne_Blues
    url: https://twitter.com/Melbourne_Blues
    desc: Follow us on Twitter
    share: true

  - name: Facebook
    icon: facebook
    username: The Melbourne Chelsea Supporters Club
    url: https://www.facebook.com/The-Melbourne-Chelsea-Supporters-Club-111143712848179/
    desc: Friend me on Facebook
    share: true

  - name: Instagram
    icon: instagram
    username: melbourne_chelsea_supporters
    url: https://www.instagram.com/melbourne_chelsea_supporters/
    desc: Follow me on Instagram
    share: false



# Social sharing protocols
# These are for automatically generating sharing metadata for FB and Twitter
# OS Protocol is for sharing the source of your site, if you're interested. For more, see osprotocol.com
protocols:
    fb_image: "/assets/logo.png"
    fb_image_width: 612
    fb_image_height: 605
    fb_image_type: "image/png"

    twitter_image: "/assets/logo.png"

    os_repo: "https://github.com/foxh0und/mcsc"
    os_rcs_type: "git"
    os_src: "git@github.com:foxh0und/mcsc.com.git"
